oauth2:
  client_id: "47129595058.apps.googleusercontent.com"
  client_secret: "UAU43KL5pxkxcrU_iNA9pCw1"
  redirect_url: "http://trustnet.gplvote.org/auth/login"
google:
  user:
    collection: "GPLVote документы сети доверия"
    main_doc: "GPLVote основной документ пользователя"
    main_doc_pages:
      user_info: "Данные пользователя"
      verify_votes: "Верификация"
      trust_votes: "Доверие"
      property_votes: "Свойства"
      actions: "Действия"
  main:
    trust_net: "GPLVote сеть доверия"
    pages:
      members: "Участники"
      options: "Настройки"
      results: "Сводные результаты"
trust_net_options:
  iteration_count: 5
  average_limit: 3

redis_for_resque:
  host: 127.0.0.1
  port: 6379
  db: 1

host_id: "bb2e763e626f11e3ba7708606e187adb"
